# Python basics Week 3: class of 24/02
working with packages and especially Numpy and Pythonic code

In [1]:
! pip install numpy


[notice] A new release of pip is available: 24.0 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import numpy
import numpy as np
from numpy import arange

## Creating arrays
arrays elements must be of the same type

In [49]:
import numpy as np

list = [1, 5, 8, 10, 3]
print(list)

array = np.array(list)
print(array)

#list --> seen as a whole and now can be added twice.
#array will store each element and multiply each element
print(list * 2)
print(array * 2)

list.append(2)
print(list)
#array.append(2) --> not possible, because of fixed size.
#print(array)

#1D arrays
print(np.arange(10)) #evenly spaced interval with given key, without upper bounds
print(np.zeros(10)) #new array with x amount of 0's
print(np.ones(10)) #new array with x amount of 0's
print(np.full(10,5)) #new array of given length with every item being a given number

print(np.random.randint(-5,6,12)) #new array filled with random numbers between given low (included), 
#given high (not included) and of a given size
print(np.random.random(15))


[1, 5, 8, 10, 3]
[ 1  5  8 10  3]
[1, 5, 8, 10, 3, 1, 5, 8, 10, 3]
[ 2 10 16 20  6]
[1, 5, 8, 10, 3, 2]
[0 1 2 3 4 5 6 7 8 9]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[5 5 5 5 5 5 5 5 5 5]
[ 5  0 -4  0  2 -4  3  0  2  1  1  0]
[0.06558873 0.82179132 0.77776575 0.24751755 0.79969843 0.99473842
 0.26961952 0.7522418  0.62158533 0.86003736 0.00952053 0.04819052
 0.27419779 0.1227931  0.89463777]


## Reshaping & converting an array

In [69]:
import numpy as np
#change the array in case of changes
array = np.random.randint(-5,6,10)
print(array)
print(array.shape) #display elements of dimensions (10,)
print(array.ndim) #number of dimensions
print("array is of type:", array.dtype)

array_float = array.astype('f') #astype() converts an array to specific datatype
#possiblities: i - integer / b - boolean / f - float / S - string / M - datetime
#what also works, you can also do the wording: str, int, bool, ...
print(array_float)

array_string = array.astype(str)
print(array_string)

#2D array
array_2D = np.reshape(array,(2,5))
print(array_2D)
print(array_2D.shape)
print(array_2D.ndim)

array_2D = np.reshape(array, (5,2))
print(array_2D)

#array_2D = np.reshape(array,(3,3)) --> needs to be perfect fit. Can't split 10 elements in 3 groups of 3.

[ 5 -2  2 -3 -2 -1 -3 -2 -3 -1]
(10,)
1
array is of type: int32
[ 5. -2.  2. -3. -2. -1. -3. -2. -3. -1.]
['5' '-2' '2' '-3' '-2' '-1' '-3' '-2' '-3' '-1']
[[ 5 -2  2 -3 -2]
 [-1 -3 -2 -3 -1]]
(2, 5)
2
[[ 5 -2]
 [ 2 -3]
 [-2 -1]
 [-3 -2]
 [-3 -1]]


## Slicing arrays
[start : end : step]
- start: starting index
- end: ending index
- step: stepsize

In [ ]:
import numpy as np
array = np.array([6,8,2,9,3,1,4,7,0,5])
print(array)

print(array[1])
print(array[1:5:1]) #[8 2 9 3]
#there is a default step if you leave out the step size. It is 0 --> : has to be there.
print(array[1:5:]) #[8 2 9 3]

#print(array[1:5:12]) --> doesn't print next number because you go beyond the limit of array. Only prints first
print(array[1:5:2]) #[8 9]

print(array[0:5:1]) #[6 8 2 9 3]
#there is a default starting point(0) if you leave out the first number. : has to be present
print(array[:5:1]) #[6 8 2 9 3]
print(array[:5:]) #[6 8 2 9 3]

print(array[::]) #prints the whole array
print(array[0::1]) #[6 8 2 9 3 1 4 7 0 5]
print(array[0:10:1])

#reverse array
print(array[::-1]) #[5 0 7 4 1 3 9 2 8 6]
print(array[10::-1]) #if you fill in the end point as 0, it will go up until index 1.
print(array[::-2]) #reverse slice with step 2 [5 7 1 9 8]


[6 8 2 9 3 1 4 7 0 5]
8
[8 2 9 3]
[8 2 9 3]
[8 9]
[6 8 2 9 3]
[6 8 2 9 3]
[6 8 2 9 3]
[6 8 2 9 3 1 4 7 0 5]
[6 8 2 9 3 1 4 7 0 5]
[6 8 2 9 3 1 4 7 0 5]
[5 0 7 4 1 3 9 2 8 6]
[5 0 7 4 1 3 9 2 8 6]
[5 7 1 9 8]


## Working with arrays

In [ ]:
import numpy as np
a = np.arange(0,10) #[0 1 2 3 4 5 6 7 8 9]
b = np.arange(9,-1,-1) #[9 8 7 6 5 4 3 2 1 0]
print(a,b)
print(a + b)
print(a - b)
print(a * b)
print(np.where(a % 2 == 0,a + 1, a))
#--> condition, x, y --> if the condition is True return x, else return y
print(np.where(b>5)) #you get indexes back
print(np.where(b>5, b, 0))

print()
b = np.reshape(b, (2,5))
print(b)
print()

print(b.sum(axis=0)) #sum of columns
print(b.sum(axis=1)) #sum of each row
print(b.cumsum(axis=1)) #sum of all elements in row, adding up element by element and showing temporary sum
print()

print(a.sum())
print(a.min())
print(a.max())

print()
print(np.sqrt(a)) #returns the square root of everything.
print(np.sqrt(a.max())) #returns square root of highest number in array

[0 1 2 3 4 5 6 7 8 9] [9 8 7 6 5 4 3 2 1 0]
[9 9 9 9 9 9 9 9 9 9]
[-9 -7 -5 -3 -1  1  3  5  7  9]
[ 0  8 14 18 20 20 18 14  8  0]
[1 1 3 3 5 5 7 7 9 9]
(array([0, 1, 2, 3]),)
[9 8 7 6 0 0 0 0 0 0]

[[9 8 7 6 5]
 [4 3 2 1 0]]

[13 11  9  7  5]
[35 10]
[[ 9 17 24 30 35]
 [ 4  7  9 10 10]]

45
0
9

[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]
3.0


### Exercise: MAGIC TABLE! It's magic time
Read in a series of numbers split by a space.
Also read in a number of rows
Calculate the sum of each column and if all the sums of all the columns are the same
--> MAGIC TABLE<br>
**input**<br>
2 7 0 8 4 1 1 0 10<br>
3<br>
**output**<br>
<pre>
2 7 0
8 4 1
1 0 10
11 11 11
MAGIC TABLE (or not)
</pre>

In [ ]:
import numpy as np
string = input()
array = np.array(string.split(" "))
array = array.astype('i') #or int
rows = int(input())

array2D = np.reshape(array, (rows, len(array) // rows))
print(array2D)

sums = array2D.sum(axis=0)
print(sums)
#np.sum(array2D, axis = 0)

total = np.sum(sums)
if total // rows == sums[0]:
    print("MAGIC TABLE")
else:
    print("NO MAGIC TABLE")


#other approach
check = True
for value in sums:
    if value != sums[0]:
        check = False
        break

if check is True:
    print("MAGIC TABLE")
else:
    print("NO MAGIC TABLE")




[[ 2  7  0  8  4]
 [ 1  1  0 10 25]]
[ 3  8  0 18 29]
