# Python basics week 3: class of 27/02
working with packages --> numpy
Maybe some pythonic code.

In [1]:
! pip install numpy


[notice] A new release of pip is available: 24.0 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


## Importing Numpy

In [2]:
import numpy
import numpy as np
from numpy import arange

## Creating arrays
array elements must have the same datatype

In [ ]:
import numpy as np
list = [1, 5, 8, 10, 3]
print(list)

array = np.array(list)
print(array)

#list --> seen as a whole and now completely added twice if multiplied
#array will store each number or element and multiply each element seperately

print(list * 2)
print(array * 2)

list.append(2)
print(list)

#array.append(2) --> not possible, fixed size!!!

#1D arrays
print(np.arange(10)) #evenly spaced digits according to indexes
print(np.zeros(10)) #fill arrays with 0's. all floats
print(np.ones(10)) #fill arrays with 1's. all floats
print(np.full(10,2)) #fills an arrays of given length with given number (datatype is same as one of number)
print(np.full(12,"hello")) #also works for any other datatype

print(np.random.randint(-5,6,10)) #prints out an array starting at lowest value included, highest not included of size
print(np.random.random(12)) #random floats of said size


[1, 5, 8, 10, 3]
[ 1  5  8 10  3]
[1, 5, 8, 10, 3, 1, 5, 8, 10, 3]
[ 2 10 16 20  6]
[1, 5, 8, 10, 3, 2]
[0 1 2 3 4 5 6 7 8 9]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[2 2 2 2 2 2 2 2 2 2]
['hello' 'hello' 'hello' 'hello' 'hello' 'hello' 'hello' 'hello' 'hello'
 'hello' 'hello' 'hello']
[ 4 -4 -1 -1 -4  5  2 -1  1  1]
[0.38368564 0.14672876 0.94924638 0.46613373 0.58069463 0.20852992
 0.76930782 0.78881511 0.54104323 0.68566655 0.24638666 0.78006524]


## Reshaping & converting arrays

In [60]:
import numpy as np

array = np.random.randint(-5,6,10)
print(array)

print(array.shape) #displays the elements of dimensions (10,)
print(array.ndim) #returns the number of dimensions
print(array.dtype)

array_float = array.astype('f')
print(array_float)
# conversion to different datatype based on key or full name of datatype
# i - int / b - boolean / f - float / M - DatTime / S - string --> use wording int, bool, float, str
array_string = array.astype(str)
print(array_string)

#2D arrays
array_2D = np.reshape(array, (5,2))
print(array_2D)
print(array_2D.shape)
print(array_2D.ndim)

#print(np.reshape(array, (3,3))) --> has to be exact same number in total to evenly split in 2D array (10 can't be split in groups of 3)


[-1  5 -3  5  4  2  5 -1 -1  1]
(10,)
1
int32
[-1.  5. -3.  5.  4.  2.  5. -1. -1.  1.]
['-1' '5' '-3' '5' '4' '2' '5' '-1' '-1' '1']
[[-1  5]
 [-3  5]
 [ 4  2]
 [ 5 -1]
 [-1  1]]
(5, 2)
2


## Slicing arrays
[start : end : step]
- start: starting index (included)
- end: end index (not included)
- step: stepsize in which you want to move through the array

In [ ]:
import numpy as np
array = np.array([6, 8, 2, 9, 3, 1, 4, 7, 0, 5])
print(array)
print(array[1:5:1]) #[8 2 9 3] 5th index not included
print(array[1:5:]) #[8 2 9 3] default step size is 1

print(array[1:5:2]) #[8 9]
print(array[0:5:1]) #[6 8 2 9 3]
print(array[:5:1])
print(array[30:35:1]) #empty list
#even if you go beyond the existing limit of the array it still runs

print(array[0:10:1])
print(array[0::1]) #default end is last index

#reversing array
#print(array[9:-1:-1])  --> to reverse difficult to reach index 0
print(array[9::-1])
print(array[-1::-1])
print(array[::-1])
#print(array[9:5:]) --> you need stepsize of -1 or higher to trigger reversing

print(array[::2]) #[6 2 3 4 0]
print(array[::-2]) #[5 7 1 9 8]

[6 8 2 9 3 1 4 7 0 5]
[8 2 9 3]
[8 2 9 3]
[8 9]
[6 8 2 9 3]
[6 8 2 9 3]
[]
[6 8 2 9 3 1 4 7 0 5]
[6 8 2 9 3 1 4 7 0 5]
[5 0 7 4 1 3 9 2 8 6]
[5 0 7 4 1 3 9 2 8 6]
[5 0 7 4 1 3 9 2 8 6]
[6 2 3 4 0]
[5 7 1 9 8]


## Working with arrays

In [102]:
import numpy as np
a = np.arange(0,10) #[0 1 2 3 4 5 6 7 8 9]
b = np.arange(9, -1, -1) #[9 8 7 6 5 4 3 2 1 0]
print("this is array a", a, "\nThis is array b",b)

print(a + b)
print(a - b)
print(a * b)
print(np.where(a % 2 == 0, a + 1, a))
# --> condition, true, false --> condition, x, y

print(np.where(b > 5))
print(np.where(b > 5, b, 0))
print()

b = np.reshape(b, (2,5))
print(b)
print()

print(b.sum(axis = 0)) #sum of columns
print(b.sum(axis = 1)) #sum of rows
print(b.cumsum(axis = 1))

print()
print(a.sum())
print(a.min())
print(a.max())
print()

print(np.sqrt(a))
print(np.sqrt(a.max()))


this is array a [0 1 2 3 4 5 6 7 8 9] 
This is array b [9 8 7 6 5 4 3 2 1 0]
[9 9 9 9 9 9 9 9 9 9]
[-9 -7 -5 -3 -1  1  3  5  7  9]
[ 0  8 14 18 20 20 18 14  8  0]
[1 1 3 3 5 5 7 7 9 9]
(array([0, 1, 2, 3]),)
[9 8 7 6 0 0 0 0 0 0]

[[9 8 7 6 5]
 [4 3 2 1 0]]

[13 11  9  7  5]
[35 10]
[[ 9 17 24 30 35]
 [ 4  7  9 10 10]]

45
0
9

[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]
3.0


### Exercise: It's magic time!
Read in a 1D array and a number of rows! 
Convert the array to 2D, calculate the sum of each column and if all the columns are equal --> you're dealing with
a magic table<br>
**input**<br>
2 7 0 8 4 1 1 0 10<br>
3<br>
**output**<br>
MAGIC TABLE OR NOT MAGIC TABLE
<pre>
2 7 0
8 4 1
1 0 10

11 11 11 --> MAGIC TABLE
</pre>

In [ ]:
import numpy as np
string = input()
rows = int(input())
array = np.array(string.split(" "))

array2D = np.reshape(array.astype(int), (rows, len(array) // rows))
print(array2D)

sums = np.sum(array2D, axis = 0) #0 is columns
print(sums)
total = np.sum(sums)

if total // rows == sums[0]:
    print("MAGIC TABLE")
else:
    print("NO MAGIC TABLE")


#or other approach
check = True
for value in sums:
    if value != sums[0]:
        check = False
        break
if check is True:
    print("MAGIC TABLE")
else:
    print("NO MAGIC TABLE")




[[ 2  7  0  8  4]
 [ 1  1  0 10 19]]
[ 3  8  0 18 23]
NO MAGIC TABLE
